/**
 * Annotation Metadata Registry
 *
 * This file will eventually be auto-generated by querying the Sparv backend.
 * For now, it's manually maintained with known Swedish annotations.
 *
 * To regenerate: npm run generate-annotations (when tool is implemented)
 */

import type { AnnotationOptions } from "./corpusConfig";

/**
 * Metadata for a single annotation type
 */
export type AnnotationMetadata = {
  /** Unique identifier (matches AnnotationOptions key) */
  id: string;

  /** i18n key for annotation label */
  labelKey: string;

  /** i18n key for help text */
  helpKey: string;

  /** Languages that support this annotation (ISO 639-3 codes) */
  supportedLanguages: string[];

  /** Whether this annotation is enabled by default */
  defaultEnabled: boolean;

  /** Sparv export module strings to add when this annotation is enabled */
  sparvModules: string[];

  /** Optional: Additional dependencies (other annotations that must be enabled) */
  requires?: string[];
};

/**
 * Registry of all available annotations
 */
export const ANNOTATION_REGISTRY: AnnotationMetadata[] = [
  {
    id: "msd",
    labelKey: "annotations.msd",
    helpKey: "annotations.msd.help",
    supportedLanguages: ["swe", "fin", "eng"], // Stanza supports many languages
    defaultEnabled: true,
    sparvModules: [
      "<token>:stanza.msd",
      "<token>:stanza.pos",
      "<token>:stanza.ufeats",
    ],
  },
  {
    id: "syntax",
    labelKey: "annotations.syntax",
    helpKey: "annotations.syntax.help",
    supportedLanguages: ["swe", "fin", "eng"], // Stanza supports many languages
    defaultEnabled: true,
    sparvModules: [
      "<token>:stanza.dephead_ref as dephead",
      "<token>:stanza.deprel",
      "<token>:stanza.ref",
    ],
  },
  {
    id: "saldo",
    labelKey: "annotations.saldo",
    helpKey: "annotations.saldo.help",
    supportedLanguages: ["swe"], // Swedish-only lexicon
    defaultEnabled: true,
    sparvModules: [
      "<token>:saldo.baseform2 as lemma",
      "<token>:saldo.lemgram as lex",
      "<token>:saldo.compwf",
      "<token>:saldo.complemgram",
    ],
  },
  {
    id: "sensaldo",
    labelKey: "annotations.sensaldo",
    helpKey: "annotations.sensaldo.help",
    supportedLanguages: ["swe"], // Swedish sentiment analysis
    defaultEnabled: true,
    sparvModules: [
      "<token>:sensaldo.sentiment_score",
      "<token>:sensaldo.sentiment_label",
    ],
  },
  {
    id: "swener",
    labelKey: "annotations.swener",
    helpKey: "annotations.swener.help",
    supportedLanguages: ["swe"], // Swedish named entity recognition
    defaultEnabled: false,
    sparvModules: [
      "swener.ne",
      "swener.ne:swener.name",
      "swener.ne:swener.ex",
      "swener.ne:swener.type",
      "swener.ne:swener.subtype",
      "<sentence>:geo.geo_context as _geocontext",
    ],
  },
  {
    id: "lexicalClasses",
    labelKey: "annotations.lexical_classes",
    helpKey: "annotations.lexical_classes.help",
    supportedLanguages: ["swe"], // BlingBring and Swedish FrameNet
    defaultEnabled: true,
    sparvModules: [
      "<token>:lexical_classes.blingbring",
      "<token>:lexical_classes.swefn",
      "<text>:lexical_classes.blingbring",
      "<text>:lexical_classes.swefn",
    ],
  },
  {
    id: "readability",
    labelKey: "annotations.readability",
    helpKey: "annotations.readability.help",
    supportedLanguages: ["swe"], // Swedish readability metrics (LIX, OVIX, NK)
    defaultEnabled: true,
    sparvModules: [
      "<text>:readability.lix",
      "<text>:readability.ovix",
      "<text>:readability.nk",
    ],
  },
  {
    id: "wsd",
    labelKey: "annotations.wsd",
    helpKey: "annotations.wsd.help",
    supportedLanguages: ["swe"], // Word sense disambiguation (Swedish)
    defaultEnabled: true,
    sparvModules: ["<token>:wsd.sense"],
  },
];

/**
 * Core annotations that are always included regardless of user selection
 */
export const CORE_ANNOTATIONS = [
  "<token>:misc.tail as _tail",
  "<token>:misc.head as _head",
  "<sentence>:misc.id",
  "<text>:misc.source",
  "<text>:misc.id as _id",
];

/**
 * Get annotations available for a specific language
 */
export function getAvailableAnnotations(
  language: string,
): AnnotationMetadata[] {
  return ANNOTATION_REGISTRY.filter((annotation) =>
    annotation.supportedLanguages.includes(language),
  );
}

/**
 * Check if an annotation is available for a language
 */
export function isAnnotationAvailable(
  annotationId: string,
  language: string,
): boolean {
  const annotation = ANNOTATION_REGISTRY.find((a) => a.id === annotationId);
  return annotation ? annotation.supportedLanguages.includes(language) : false;
}

/**
 * Get default annotation options for a language
 */
export function getDefaultAnnotations(
  language: string,
): Partial<AnnotationOptions> {
  const available = getAvailableAnnotations(language);
  const defaults: any = {};

  for (const annotation of available) {
    if (annotation.id !== "datetime") {
      // Special case
      defaults[annotation.id] = annotation.defaultEnabled;
    }
  }

  return defaults;
}

/**
 * Get Sparv modules for enabled annotations
 */
export function getSparvModules(annotations: AnnotationOptions): string[] {
  const modules: string[] = [...CORE_ANNOTATIONS];

  for (const annotation of ANNOTATION_REGISTRY) {
    const value = (annotations as any)[annotation.id];
    if (value === true) {
      // Enabled
      modules.push(...annotation.sparvModules);
    }
  }

  return modules;
}

/**
 * Parse annotations from Sparv export modules
 */
export function parseAnnotations(
  exportModules: string[] | undefined,
): Partial<AnnotationOptions> {
  if (!exportModules) return {};

  const annotations: any = {};

  for (const annotation of ANNOTATION_REGISTRY) {
    // Check if any of this annotation's Sparv modules are present
    const isEnabled = annotation.sparvModules.some((module) =>
      exportModules.includes(module),
    );
    annotations[annotation.id] = isEnabled;
  }

  return annotations;
}
